name: notes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.9
  flutter_heatmap_calendar: ^1.0.5
  shared_preferences: ^2.2.3
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1   # ✅ only keep this for app icon

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900

  assets:
    - assets/images/front.png
    - assets/images/google.png
    - assets/images/github.png
    - assets/images/facebook.png
    - assets/images/key.png
    - assets/images/otp.png
    - assets/images/waveform.png
    - assets/images/search.png
    - assets/images/home.png
    - assets/images/play.png
    - assets/images/folder.png
    - assets/images/calender.png

# ✅ Config for flutter_launcher_icons
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"   # <-- replace with your app icon image
  adaptive_icon_background: "#FFFFFF"        # solid background (can be your brand color)
  adaptive_icon_foreground: "assets/images/app_icon.png"
